services:
  # 1. API (Backend en NestJS)
  - type: web
    name: skoolia-api
    env: node
    plan: free
    rootDir: apps/api
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start:prod
    envVars:
      - key: DATABASE_URL
        sync: false # Deberás pegar la URL de Neon en el dashboard de Render
      - key: PORT
        value: 8000
